services:
  nginx:
    container_name: nginx
    image: nginx:latest
    build: ./frontend
    depends_on:
      - api
    volumes:
    - /Users/amirabendhia/Desktop/push/frontend/front/:/var/www/html/
    ports:
      - '443:443'
    networks:
      - network
    # restart: always
  api:
    container_name: api
    image: python:3.12-alpine
    build: ./backend
    depends_on:
      - postgres
    volumes:
      - /Users/amirabendhia/Desktop/push/backend/api/:/app
    ports:
      - '8000:8000'
    networks:
      - network
    restart: always
    env_file:
      - /Users/amirabendhia/Desktop/push/.env
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - network
    restart: always
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - network
    restart: always
  postgres_exporter:
    image: wrouesnel/postgres_exporter:latest  # PostgreSQL Exporter image
    container_name: postgres_exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://gohan:dyueiv483%3A%3B%3E20f@postgres:5432/datastore?sslmode=disable  # DSN format for PostgreSQL connection
    ports:
      - "9187:9187"  # Expose the PostgreSQL exporter on port 9187
    networks:
      - network
    depends_on:
      - postgres
    restart: always
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set Grafana admin password
    ports:
      - "3000:3000"
    networks:
      - network
    depends_on:
      - prometheus
    restart: always


networks:
    network:

# volumes:
#   postgres_data:
#     driver: local
