# Generated by Django 5.1.3 on 2024-12-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_oauth_id_customuser_oauth_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='oauth_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='oauth_provider',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.URLField(blank=True, default='https://example.com/default-photo.jpg', null=True),
        ),
    ]
