# Generated by Django 5.1.4 on 2024-12-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.CharField(blank=True, default='https://cdn-images-3.listennotes.com/podcasts/two-dead-pines/lsd-trip-report-qe0e3pjyglg-usiahzq6kye.1400x1400.jpg?_gl=1*2qe68d*_ga*odmxnduyotgxlje3mzmxndk5mzy.*_ga_t0pze2z7l4*mtczmze0otkzns4xljaumtczmze0otk0my41mi4wlja.', max_length=2000, null=True),
        ),
    ]
